---
title: "DataEducacion"
author: "Christian Castro, Vivian Romero, Ian Meza"
date: "30-09-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```
```{r cuerpo1, echo=FALSE, results='hide'}
library(ggplot2)
library(reticulate)
library(knitr)
library(gghighlight)
library(magrittr)
library(readr)
library(ape)
library(ggdendro)
library(bookdown)
library(janitor)
require(rgdal)
require(ggplot2)
library(sf)
library(ggrepel)
library(gganimate)
#library(xlsx)
library(readxl)
```


```{r cuerpo3, echo=FALSE, results='hide'}

matricula <- read_xlsx("C:/Users/Ian/Documents/SudAustral/DataEducacion/2011.xlsx")

# a repetir:
matricula_subset_a_repetir <- matricula[,c(-1,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25)]

e <- matricula_subset_a_repetir[rep(seq_len(nrow(matricula_subset_a_repetir)), each = 16), ]

write.table(e,'e_2011.csv', row.names = FALSE, col.names = TRUE,append = FALSE,sep = ",")
dt <- matricula[,c(-1,-2,-3,-4,-5,-6,-7,-8,-9)]
dt_t <- data.frame(t(dt))
matricula_stack <- stack(dt_t)

write.table(matricula_stack,'matricula_s_2011.csv',row.names = FALSE,col.names = TRUE,append = FALSE,sep = ",")

coln <- data.frame(colnames(dt, do.NULL = TRUE, prefix = "col"))
coln_r <- coln[rep(seq_len(nrow(coln)), times = 11026), ]
coln_r

write.table(coln_r,'headers.csv',row.names = FALSE,col.names = TRUE,append = FALSE,sep = ",")

```


